=== nguyenthibinh31082001/SemII/1.Modern Markup for Data Interchange(JSON)/BT Lab/XML_Session 3_Lab2/Lab 2/src/BTTH_Lab2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT SaleDetails (Sale*)>
    
    <!ELEMENT Sale (BillNumber, Date, Branch, Item, Payment)>
    <!ELEMENT BillNumber (#PCDATA)>
    <!ELEMENT Date (#PCDATA)>
    <!ELEMENT Branch (#PCDATA)>
    <!ELEMENT Item (Number, Name, Code, Quantity, Price, Discount, Total)>
    <!ELEMENT Number (#PCDATA)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Code (#PCDATA)>
    <!ELEMENT Quantity (#PCDATA)>
    <!ELEMENT Price (#PCDATA)>
    <!ELEMENT Discount (#PCDATA)>
    <!ELEMENT Total (#PCDATA)>
    <!ELEMENT Payment (CardName, CustomerName, CardNumber, AccountNumber,GrandTotal)>
    <!ELEMENT CardName (#PCDATA)>
    <!ELEMENT CustomerName (#PCDATA)>
    <!ELEMENT CardNumber (#PCDATA)>
    <!ELEMENT AccountNumber (#PCDATA)>
    <!ELEMENT GrandTotal (#PCDATA)>
    <!ATTLIST Payment Mode (Card|Cash) #REQUIRED>
    <!ATTLIST Name Category (Apparel|Footwear) "Apparel">
    <!ATTLIST CardName Type (Credit|Debit) "Credit">
    <!ENTITY VH "Van Huesen">
    <!ENTITY AS "Allen Solly">

=== nguyenthibinh31082001/SemII/1.Modern Markup for Data Interchange(JSON)/BT Lab/XML_Session 3_Lab2/Lab 2/src/BTTH_Lab2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--bài tập thực hành 2-->
<!DOCTYPE SaleDetails SYSTEM "BTTH_Lab2.dtd">
<!--<!DOCTYPE SaleDetails [
    <!ELEMENT SaleDetails (Sale+)>
    <!ELEMENT Sale (BillNumber, Date, Branch, Item, Payment)>
    <!ELEMENT BillNumber (#PCDATA)>
    <!ELEMENT Date (#PCDATA)>
    <!ELEMENT Branch (#PCDATA)>
    <!ELEMENT Item (#PCDATA)>
    <!ELEMENT Payment (#PCDATA)>
    <!ATTLIST Payment chedo (Card|Cash) #REQUIRED>
    <!ENTITY VH "Van Huesen">
    
]>-->
<SaleDetails>
    <Sale>
        <BillNumber>4568</BillNumber>
        <Date>23/02/2007</Date>
        <Branch>Hampshire</Branch>
        <Item>
            <Number>1</Number>
            <Name Category="Apparel">&VH; Jeans</Name>
            <Code>2323</Code>
            <Quantity>1</Quantity>
            <Price>200</Price>
            <Discount>10</Discount>
            <Total>180</Total>
        </Item>
        <Payment Mode="Card">
            <CardName Type="Credit">&AS;</CardName>
            <CustomerName>Allan</CustomerName>
            <CardNumber>99044993</CardNumber>
            <AccountNumber>77688906</AccountNumber>
            <GrandTotal>180</GrandTotal>
        </Payment>
    </Sale>
</SaleDetails>
