=== nguyenthibinh31082001/SemII/1.Modern Markup for Data Interchange(JSON)/BT Lab/XML_Lab 3/src/BTTH0_Lab3.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="category" type="xs:string"/>
                            <xs:element name="year" type="xs:string"/>
                            <xs:element name="edition" type="xs:string"/>
                            <xs:element name="price" type="xs:string"/>
                        </xs:sequence>
                    <xs:attribute name="ISBN" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nguyenthibinh31082001/SemII/1.Modern Markup for Data Interchange(JSON)/BT Lab/XML_Lab 3/src/BTTH0_Lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<bookstore
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='BTTH0_Lab3.xsd'>
    <book ISBN="123456">
        <title>XML Đơn giản</title>
        <author>Quế Ngọc Hải</author>
        <category>Lập trình</category>
        <year>2016</year>
        <edition>Đoàn Nguyên Đức</edition>
        <price>$69</price>
    </book>

</bookstore>
